[project]
# The title of the index page.
title = "RotGUI"
# Copyright information displayed on the footer of each page
copyright = "2019-2024 Association of Universities for Research in Astronomy, Inc. (AURA)"

[project.python]
# pyproject.toml package name, fills out unseen metadata
package = "ts_rotgui" # should match the name that importlib.metadata uses/pyproject.toml name
documentation_url_key = "documentation"
github_url_key = "repository"

[sphinx]
extensions = ["sphinx-jsonschema"]

[sphinx.intersphinx.projects]
ts-xml = "https://ts-xml.lsst.io"
salobj = "https://ts-salobj.lsst.io"
python = "https://docs.python.org/3.13/"
